apiVersion: v1
kind: Service
metadata:
  name: {{ include "order1.fullname" . }}
  labels:
    {{- include "order1.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      #targetPort: http
      protocol: TCP
      name: http
      nodePort: {{ .Values.service.nodePort }}
  selector:
    {{- include "order1.selectorLabels" . | nindent 4 }}
